# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [4]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [9]:
weather_file = "../output_data/cities.csv"

weather_df = pd.read_csv(weather_file)
del weather_df["Unnamed: 0"]
weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Coyhaique,-45.5752,-72.0662,7.34,93,75,1.03,CL,1662874424
1,Punta Arenas,-53.1500,-70.9167,4.06,81,0,3.60,CL,1662874425
2,Northam,51.0333,-4.2167,15.90,88,97,3.72,GB,1662874425
3,Nome,64.5011,-165.4064,8.04,76,75,4.12,US,1662874426
4,Fuerte Olimpo,-21.0415,-57.8738,16.16,48,7,2.25,PY,1662874427
...,...,...,...,...,...,...,...,...,...
536,Amahai,-3.3333,128.9167,27.12,79,99,2.06,ID,1662874781
537,São Filipe,14.8961,-24.4956,25.91,82,16,0.51,CV,1662874782
538,Port Augusta,-32.5000,137.7667,17.70,49,1,5.69,AU,1662874782
539,La Ronge,55.1001,-105.2842,13.14,58,0,2.57,CA,1662874783
540,Aberdeen,57.1437,-2.0981,9.16,93,74,0.51,GB,1662874784

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [8]:
gmaps.configure(api_key=g_key)

In [17]:
locations = weather_df[["Lat", "Lng"]]
humidity = weather_df["Humidity"].astype(float)

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=100,
                                 point_radius=2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [20]:
perfect_weather_df = weather_df
perfect_weather_df = perfect_weather_df.loc[perfect_weather_df["Max Temp"] < 27]
perfect_weather_df = perfect_weather_df.loc[perfect_weather_df["Max Temp"] > 21]
perfect_weather_df = perfect_weather_df.loc[perfect_weather_df["Wind Speed"] < 4.5]
perfect_weather_df = perfect_weather_df.loc[perfect_weather_df["Cloudiness"] == 0]

perfect_weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
20,Gainesville,29.6516,-82.3248,23.37,87,0,2.57,US,1662874228
115,Fethiye,36.6217,29.1164,23.93,26,0,0.90,TR,1662874535
129,Cayenne,4.9333,-52.3333,24.02,100,0,0.51,GF,1662874543
148,Carutapera,-1.1950,-46.0200,24.15,89,0,2.16,BR,1662874554
181,Wuda,39.4994,106.7117,25.18,29,0,4.32,CN,1662874574
246,Mumbwa,-14.9783,27.0619,22.58,26,0,2.78,ZM,1662874615
293,Saint George,37.1041,-113.5841,24.24,59,0,1.54,US,1662874359
306,Abu Samrah,35.3029,37.1841,26.86,25,0,2.87,SY,1662874649
316,San Joaquin,37.9333,-121.3011,25.13,56,0,3.60,US,1662874655
325,Laguna,38.4210,-121.4238,24.69,59,0,4.12,US,1662874661
328,Xining,36.6167,101.7667,21.10,37,0,1.51,CN,1662874503
332,Pacific Grove,36.6177,-121.9166,22.12,80,0,2.57,US,1662874665
342,Beloha,-25.1667,45.0500,25.53,41,0,1.92,MG,1662874670
350,Nālūt,30.3333,10.8500,25.60,27,0,3.30,LY,1662874675
373,Lockhart,28.6194,-81.4426,25.05,96,0,0.00,US,1662874687
375,Erciş,39.0287,43.3586,21.05,23,0,1.13,TR,1662874688
443,Seoul,37.5683,126.9778,25.78,53,0,2.57,KR,1662874121
455,Salinas,36.6777,-121.6555,24.34,74,0,2.57,US,1662874730
463,Lompoc,34.6391,-120.4579,23.90,81,0,0.00,US,1662874733
479,Tsumeb,-19.2333,17.7167,21.44,16,0,2.99,NaN,1662874744
484,Rincon,32.2960,-81.2354,26.59,96,0,2.06,US,1662874746
492,Griffith,41.5284,-87.4237,22.16,92,0,0.00,US,1662874753
501,Kalabo,-14.9700,22.6814,21.41,24,0,3.30,ZM,1662874758

In [25]:
perfect_locations = perfect_weather_df[["Lat", "Lng"]]
perfect_humidity = perfect_weather_df["Humidity"].astype(float)

perfect_fig = gmaps.figure()

perfect_heat_layer = gmaps.heatmap_layer(perfect_locations, weights=perfect_humidity, dissipating=False, max_intensity=100,
                                 point_radius=2)

perfect_fig.add_layer(perfect_heat_layer)

perfect_fig

Figure(layout=FigureLayout(height='420px'))

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [31]:
hotel_df = perfect_weather_df

hotel_df["Hotel Name"] = ""

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {
    "radius": 5000,
    "rankby": "prominence",
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key}

for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    city = row["City"]
    params["location"] = f'{lat},{lng}'
                        
    response = requests.get(base_url, params=params).json()
    results = response["results"]
 
    try:
        print(f"Closest {city} hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except:
        print(f"Missing field/result for {city}... skipping.")

Closest Gainesville hotel is AC Hotel Gainesville Downtown.
Closest Fethiye hotel is Club & Hotel Letoonia.
Closest Cayenne hotel is Grand Hotel Montabo.
Closest Carutapera hotel is Center Hotel.
Closest Wuda hotel is Xinxin Hotel.
Closest Mumbwa hotel is Fourways Challets Inn.
Closest Saint George hotel is The Advenire, Autograph Collection.
Missing field/result for Abu Samrah... skipping.
Closest San Joaquin hotel is University Plaza Waterfront Hotel.
Closest Laguna hotel is Hampton Inn & Suites Sacramento-Elk Grove Laguna I-5.
Closest Xining hotel is Sofitel Xining.
Closest Pacific Grove hotel is Hotel 1110.
Missing field/result for Beloha... skipping.
Missing field/result for Nālūt... skipping.
Closest Lockhart hotel is Sheraton Orlando North Hotel.
Closest Erciş hotel is DİLMAN GOLD OTEL ERCİŞ.
Closest Seoul hotel is Four Seasons Hotel Seoul.
Closest Salinas hotel is Hampton Inn & Suites Salinas.
Closest Lompoc hotel is Hilton Garden Inn Lompoc.
Closest Tsumeb hotel is Minen Hotel.
Missing field/result for Rincon... skipping.
Closest Griffith hotel is Holiday Inn Express & Suites Hammond, an IHG Hotel.
Closest Kalabo hotel is Sikakubete Guest House Kalabo Town Council.

In [32]:
hotel_df = hotel_df[hotel_df['Hotel Name'].notna()]
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
20,Gainesville,29.6516,-82.3248,23.37,87,0,2.57,US,1662874228,AC Hotel Gainesville Downtown
115,Fethiye,36.6217,29.1164,23.93,26,0,0.90,TR,1662874535,Club & Hotel Letoonia
129,Cayenne,4.9333,-52.3333,24.02,100,0,0.51,GF,1662874543,Grand Hotel Montabo
148,Carutapera,-1.1950,-46.0200,24.15,89,0,2.16,BR,1662874554,Center Hotel
181,Wuda,39.4994,106.7117,25.18,29,0,4.32,CN,1662874574,Xinxin Hotel
246,Mumbwa,-14.9783,27.0619,22.58,26,0,2.78,ZM,1662874615,Fourways Challets Inn
293,Saint George,37.1041,-113.5841,24.24,59,0,1.54,US,1662874359,"The Advenire, Autograph Collection"
306,Abu Samrah,35.3029,37.1841,26.86,25,0,2.87,SY,1662874649,
316,San Joaquin,37.9333,-121.3011,25.13,56,0,3.60,US,1662874655,University Plaza Waterfront Hotel
325,Laguna,38.4210,-121.4238,24.69,59,0,4.12,US,1662874661,Hampton Inn & Suites Sacramento-Elk Grove Lagu...
328,Xining,36.6167,101.7667,21.10,37,0,1.51,CN,1662874503,Sofitel Xining
332,Pacific Grove,36.6177,-121.9166,22.12,80,0,2.57,US,1662874665,Hotel 1110
342,Beloha,-25.1667,45.0500,25.53,41,0,1.92,MG,1662874670,
350,Nālūt,30.3333,10.8500,25.60,27,0,3.30,LY,1662874675,
373,Lockhart,28.6194,-81.4426,25.05,96,0,0.00,US,1662874687,Sheraton Orlando North Hotel
375,Erciş,39.0287,43.3586,21.05,23,0,1.13,TR,1662874688,DİLMAN GOLD OTEL ERCİŞ
443,Seoul,37.5683,126.9778,25.78,53,0,2.57,KR,1662874121,Four Seasons Hotel Seoul
455,Salinas,36.6777,-121.6555,24.34,74,0,2.57,US,1662874730,Hampton Inn & Suites Salinas
463,Lompoc,34.6391,-120.4579,23.90,81,0,0.00,US,1662874733,Hilton Garden Inn Lompoc
479,Tsumeb,-19.2333,17.7167,21.44,16,0,2.99,NaN,1662874744,Minen Hotel
484,Rincon,32.2960,-81.2354,26.59,96,0,2.06,US,1662874746,
492,Griffith,41.5284,-87.4237,22.16,92,0,0.00,US,1662874753,"Holiday Inn Express & Suites Hammond, an IHG H..."
501,Kalabo,-14.9700,22.6814,21.41,24,0,3.30,ZM,1662874758,Sikakubete Guest House Kalabo Town Council

In [33]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [34]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))